# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(help_text='Student for whom payment is made', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='student.student'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(help_text='Parent payment this history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='parent.payment'),
        ),
        migrations.AlterUniqueTogether(
            name='paymenthistory',
            unique_together={('payment', 'installment_number')},
        ),
    ]
