# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission_office', '0001_initial'),
        ('classroom', '0003_initial'),
        ('employee', '0001_initial'),
        ('level', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='level_applying_for',
            field=models.ForeignKey(help_text='Level applying for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='level.level'),
        ),
        migrations.AddField(
            model_name='admission',
            name='processed_by',
            field=models.ForeignKey(help_text='Employee who processed this admission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_admissions', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_room',
            field=models.ForeignKey(help_text='Classroom where attendance was taken', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='classroom.class'),
        ),
    ]
