# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission_office', '0002_initial'),
        ('classroom', '0003_initial'),
        ('employee', '0001_initial'),
        ('level', '0002_initial'),
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(help_text='Student for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(help_text='Subject for this attendance', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher who took the attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_attendance', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_room',
            field=models.ForeignKey(help_text='Room where exam will be conducted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classroom.class'),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilator',
            field=models.ForeignKey(help_text='Employee invigilating this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(help_text='Level this exam is for', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='level.level'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section this exam is for (null for all sections)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='level.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(help_text='Subject for this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(help_text='Exam this result is for', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='admission_office.exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='graded_by',
            field=models.ForeignKey(help_text='Employee who graded this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exams', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(help_text='Student who took the exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
    ]
