# Generated by Django 5.2.5 on 2025-09-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_office', '0003_initial'),
        ('subject', '0006_remove_subject_level_remove_subject_sections_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject for this attendance (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='subject.subject'),
        ),
    ]
