# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0003_initial'),
        ('level', '0001_initial'),
        ('subject', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelsubject',
            name='subject',
            field=models.ForeignKey(help_text='Subject for this level', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher for this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='level',
            field=models.ForeignKey(help_text='Level this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='level.level'),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Primary classroom for this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_room', to='classroom.class'),
        ),
        migrations.AlterUniqueTogether(
            name='levelsubject',
            unique_together={('level', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('level', 'sec_no')},
        ),
    ]
