# Generated by Django 5.2.5 on 2025-09-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsubject',
            name='level',
            field=models.ForeignKey(help_text='Level this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='level.level'),
        ),
    ]
