# Generated by Django 5.2.5 on 2025-09-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_initial'),
        ('level', '0003_alter_levelsubject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='classroom',
            field=models.OneToOneField(blank=True, help_text='Single classroom assigned to this level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level', to='classroom.class'),
        ),
    ]
