# Generated by Django 5.2.5 on 2025-09-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_level_classroom'),
        ('subject', '0006_remove_subject_level_remove_subject_sections_count_and_more'),
        ('teacher', '0003_teacher_address_teacher_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='Section receiving the subject', on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='level.section')),
                ('subject', models.ForeignKey(help_text='Subject assigned to the section', on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='subject.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher assigned to teach this subject in the section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_subjects', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Section Subject',
                'verbose_name_plural': 'Section Subjects',
                'db_table': 'section_subjects',
                'ordering': ['section', 'subject'],
                'unique_together': {('section', 'subject')},
            },
        ),
    ]
