# Generated by Django 5.2.5 on 2025-09-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_initial'),
        ('level', '0003_alter_levelsubject_level'),
        ('subject', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Level this subject is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_subjects', to='level.level'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sections_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of sections for this subject'),
        ),
        migrations.CreateModel(
            name='SubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.PositiveIntegerField(default=30, help_text='Maximum number of students in this section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='Classroom assigned to this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_sections', to='classroom.class')),
                ('level', models.ForeignKey(help_text='Level this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='level_subject_sections', to='level.level')),
                ('section', models.ForeignKey(help_text='Section for this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subject_sections', to='level.section')),
                ('subject', models.ForeignKey(help_text='Subject this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subject_sections', to='subject.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher assigned to this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_sections', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Subject Section',
                'verbose_name_plural': 'Subject Sections',
                'db_table': 'subject_sections',
                'ordering': ['subject', 'section'],
                'unique_together': {('subject', 'section')},
            },
        ),
    ]
