# Generated by Django 5.2.5 on 2025-09-04 04:52

from django.db import migrations


def populate_subject_levels(apps, schema_editor):
    """Populate level field for existing subjects"""
    Subject = apps.get_model('subject', 'Subject')
    Level = apps.get_model('level', 'Level')
    
    # Get the first available level
    first_level = Level.objects.first()
    
    if first_level:
        # Update all subjects that don't have a level
        Subject.objects.filter(level__isnull=True).update(level=first_level)


def reverse_populate_subject_levels(apps, schema_editor):
    """Reverse operation - set level to None"""
    Subject = apps.get_model('subject', 'Subject')
    Subject.objects.all().update(level=None)


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_level_subject_sections_count_subjectsection'),
    ]

    operations = [
        migrations.RunPython(populate_subject_levels, reverse_populate_subject_levels),
    ]
