# Generated by Django 5.2.5 on 2025-09-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_alter_subject_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
    ]
