# Generated by Django 5.2.5 on 2025-09-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_remove_subject_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sections_count',
        ),
        migrations.DeleteModel(
            name='SubjectSection',
        ),
    ]
