# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent participant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='parent.parent'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student participant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='student.student'),
        ),
        migrations.AddField(
            model_name='eventresource',
            name='event',
            field=models.ForeignKey(help_text='Event this resource is for', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'student', 'employee', 'parent', 'external_name')},
        ),
    ]
