# Generated by Django 5.2.5 on 2025-09-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialsummary',
            new_name='financial_s_period__d6fcf2_idx',
            old_name='financial__period__6a9d4b_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='financial_t_transac_a3436b_idx',
            old_name='financial__transac_3c8b8f_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='financial_t_categor_442f14_idx',
            old_name='financial__categor_9b8c3a_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='financial_t_transac_463e97_idx',
            old_name='financial__transac_8d4a5e_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='financial_t_referen_3b418f_idx',
            old_name='financial__referen_7f2e1c_idx',
        ),
    ]
