# Generated by Django 5.2.5 on 2025-09-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('sal_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly Salary'), ('bonus', 'Bonus'), ('overtime', 'Overtime'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('other', 'Other')], default='monthly', help_text='Type of salary payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Salary amount', max_digits=10)),
                ('month', models.CharField(help_text="Month for this salary (e.g., 'January 2025')", max_length=20)),
                ('pay_date', models.DateField(help_text='Scheduled payment date')),
                ('paid_date', models.DateField(blank=True, help_text='Actual payment date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', help_text='Payment status', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Basic salary amount', max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, help_text='Total allowances', max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Total deductions', max_digits=10)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime hours worked', max_digits=5)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime rate per hour', max_digits=8)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax deduction amount', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Net salary after all calculations', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this salary payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee receiving the salary', on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Salary',
                'verbose_name_plural': 'Employee Salaries',
                'db_table': 'employee_salaries',
                'ordering': ['-pay_date'],
                'unique_together': {('employee', 'month', 'salary_type')},
            },
        ),
    ]
