# Generated by Django 5.2.5 on 2025-09-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='achievements',
            field=models.TextField(blank=True, help_text='Awards and achievements', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications and licenses', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.TextField(blank=True, help_text='Educational background and degrees', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_details',
            field=models.TextField(blank=True, help_text='Detailed work experience', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Teacher profile photo', null=True, upload_to='teacher_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(blank=True, help_text='Teaching skills and competencies', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='social_links',
            field=models.JSONField(blank=True, help_text='Social media and professional links', null=True),
        ),
    ]
