# Generated by Django 5.2.5 on 2025-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_achievements_teacher_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, help_text="Teacher's personal address", null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, help_text="Teacher's personal email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text="Teacher's personal phone number", max_length=15, null=True),
        ),
    ]
