# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_name', models.CharField(help_text='Department name (e.g., Computer Science, Mathematics)', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)])),
                ('location', models.CharField(help_text='Physical location of the department', max_length=200)),
                ('d_type', models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('support', 'Support'), ('finance', 'Finance'), ('hr', 'Human Resources')], default='academic', help_text='Type of department', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the department', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['d_name'],
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the financial report')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Total fee amount', max_digits=10)),
                ('fee_collection_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee collection rate percentage', max_digits=5)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, help_text='Total expense amount', max_digits=10)),
                ('report', models.TextField(help_text='Detailed financial report')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the financial report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance Report',
                'verbose_name_plural': 'Finance Reports',
                'db_table': 'finances',
                'ordering': ['-date'],
            },
        ),
    ]
