# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Head of the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='finance',
            name='department',
            field=models.ForeignKey(help_text='Department this finance report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='department.department'),
        ),
        migrations.AlterUniqueTogether(
            name='finance',
            unique_together={('department', 'date')},
        ),
    ]
