# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='booked_by',
            field=models.ForeignKey(help_text='Employee who made the booking', on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='class_room',
            field=models.ForeignKey(help_text='Room being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classroom.class'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='class_room',
            field=models.ForeignKey(help_text='Room for this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classroom.class'),
        ),
    ]
