# Generated by Django 5.2.5 on 2025-09-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_initial'),
        ('level', '0001_initial'),
        ('subject', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='level',
            field=models.ForeignKey(help_text='Level this class is for', on_delete=django.db.models.deletion.CASCADE, to='level.level'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section this class is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='level.section'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher teaching this class', on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('class_room', 'day_of_week', 'start_time', 'academic_year')},
        ),
    ]
